### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by thanhtuyenne** [Thuancvce150378/Jobee#3]

**Comment by thanhtuyenne** [comment]
Trong table, cột ID đang bị overflow text
container đang bị dư phần dưới

**Comment by Thuancvce150378** [comment]
đã giải quyết

**Comment by Thuancvce150378** [comment]
- [ ] input size chưa họp lý label và input quá chật

**Comment by Thuancvce150378** [comment]
- [x] Nút `view` chưa có phần sử lý chuyển trang
- [x] nut `delete` chưa có confirm
- [x] Search chưa có form
- [x] chưa có phần xử lý cho accept và reject bên verify
- [x] phần description của `Verify Request` chưa có khả năng thu gọn

**Comment by thanhtuyenne** [comment]
thêm phần hiện lên popup confirm khi accept verify request

**Comment by thanhtuyenne** [comment]
xóa nút delete bên manage user
